services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: degustware
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - degustware_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  api:
    build: ./api
    container_name: api
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: degustware
    ports:
      - "3000:3000"  # Porta interna para o container da API
    depends_on:
      db:
        condition: service_healthy
    networks:
      - degustware_network

  front:
    build: ./front
    container_name: front
    expose:
      - "80"  # Expõe a porta internamente, sem usar a porta 80 do host
    networks:
      - degustware_network
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"  # Só o Nginx expõe a porta 80 para o host
    depends_on:
      - front
      - api
    networks:
      - degustware_network

volumes:
  db_data:

networks:
  degustware_network:
    driver: bridge
