version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: degustware  # Este é o nome do banco de dados
    ports:
      - "3306:3306"
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_NAME: degustware  # Corrigido aqui para degustware
    depends_on:
      - mysql

  front:
    build: ./front
    ports:
      - "80:80"
    depends_on:
      - api
