version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdatabase
    ports:
      - "3306:3306"

  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_NAME: yourdatabase
    depends_on:
      - mysql

  front:
    build: ./front
    ports:
      - "80:80"
    depends_on:
      - api
