services:
  db:
    image: mysql:8
    restart: always
    container_name: mysql_db
    env_file: 
      - ./api/.env
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - degustware_network

  api:
    build: ./api
    restart: always
    container_name: api
    env_file: 
      - .env
    depends_on:
      - db
    networks: 
      - degustware_network

  front:
    build: ./front
    restart: always
    container_name: front
    depends_on:
      - api
    networks: 
      - degustware_network

  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/degustware.com.br/fullchain.pem:/etc/letsencrypt/live/degustware.com.br/fullchain.pem:ro
      - /etc/letsencrypt/live/degustware.com.br/privkey.pem:/etc/letsencrypt/live/degustware.com.br/privkey.pem:ro
    ports:
      - "80:80"  # Porta HTTP
      - "443:443"  # Porta HTTPS
    depends_on:
      - front
    networks: 
      - degustware_network

volumes:
  db_data:

networks:
  degustware_network:
    driver: bridge
