console.log("Hello, World!")
console.log("Atualizado")
console.log("Atualizado 2")
console.log("Atualizado 3")
console.log("Atualizado 4")
console.log("Atualizado 5")
console.log("Atualizado 6")
console.log("Atualizado 7")
console.log("Atualizado 8")
console.log("Atualizado 9")
console.log("Atualizado 10")