services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local_password
      MYSQL_DATABASE: syscon_bd
    command: --log-bin-trust-function-creators=1
    volumes:
      - db:/var/lib/mysql
      - ../../public/backups/backup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
volumes:
  db:
