services:
  db:
    image: mysql
    restart: always
    env_file:
      - ../.env
    command: --log-bin-trust-function-creators=1
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db:
